import Head from "next/head";
import Hauptcomponent from "../components/Hauptcomponent";
import Header from "../components/header";
import Layout from "../components/layout";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lebenslauf-Kiril Shterjov</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header />
        <Hauptcomponent/>
      </Layout>
    </div>
  );
}
